# -*- coding: utf-8 -*-
"""
语言管理器
用于处理应用程序的中英文切换功能
"""

class LanguageManager:
    def __init__(self):
        self.current_language = 'zh'  # 默认中文
        self.translations = {
            'zh': {
                # 主窗口
                'app_title': 'Hurricane Community Store',
                'login': '登录',
                'register': '注册',
                'home': '商城',
                'cart': '购物车',
                'profile': '个人中心',
                'admin': '管理员',
                'csgo_server': 'CSGO服务器',
                'logout': '退出登录',
                'language': '语言',
                'switch_to_english': '切换到英文',
                'switch_to_chinese': '切换到中文',
                
                # 登录页面
                'welcome_to': '欢迎来到',
                'username': '用户名',
                'password': '密码',
                'login_button': '登录',
                'register_button': '注册',
                'back_to_login': '返回登录',
                'forgot_password': '忘记密码',
                'remember_me': '记住我',
                
                # 注册页面
                'confirm_password': '确认密码',
                'email': '邮箱',
                'register_title': '注册',
                'confirm_register': '确认注册',
                'steam_bind': 'Steam绑定',
                'bind_steam': '绑定Steam',
                'enter_captcha': '请输入图片中的验证码',
                'captcha_success': '✓ 验证成功',
                'captcha_error': '❌ 验证码错误，请重新输入',
                'enter_4_digits': '请输入4位数字',
                
                # 商城页面
                'shop_title': '商城',
                'product_name': '商品名称',
                'price': '价格',
                'description': '描述',
                'add_to_cart': '加入购物车',
                'buy_now': '立即购买',
                'search': '搜索',
                'category': '分类',
                'all_categories': '全部分类',
                
                # 购物车页面
                'cart_title': '购物车',
                'quantity': '数量',
                'total': '总计',
                'checkout': '结算',
                'remove': '移除',
                'clear_cart': '清空购物车',
                'empty_cart': '购物车为空',
                
                # 个人中心页面
                'profile_title': '个人中心',
                'personal_center': '👤 个人中心',
                'user_info': '📋 用户信息',
                'steam_account_binding': '🎮 Steam 账户绑定',
                'enter_steam_id': '请输入您的 Steam ID',
                'bind_steam': '🔗 绑定Steam',
                'points_recharge': '💰 积分充值',
                'current_exchange_rate': '⭐ 当前兑换比例: 1元 = {exchange_rate}积分',
                'recharge_amount': '💳 充值金额:',
                'enter_amount_yuan': '请输入充值金额（元）',
                'will_get_points': '将获得积分: {points}',
                'will_get_points_0': '将获得积分: 0',
                'payment_method': '💰 支付方式:',
                'recharge_now': '🚀 立即充值',
                'transaction_records': '📊 交易记录',
                'time': '时间',
                'type': '类型',
                'amount': '金额',
                'description': '描述',
                'username_label': '用户名',
                'account_type': '账户类型',
                'display_name': '显示名称',
                'email': '邮箱',
                'points_balance': '积分余额',
                'steam_account': 'Steam账号',
                'not_bound_steam': '未绑定Steam账号',
                'please_login_first': '请先登录',
                'please_enter_steam_id': '请输入Steam ID',
                'steam_bind_success': 'Steam账号绑定成功',
                'bind_failed': '绑定失败',
                'amount_must_greater_zero': '充值金额必须大于0',
                'max_recharge_limit': '单次充值金额不能超过10000元',
                'recharge_confirmation': '充值信息确认',
                'payment_amount': '充值金额',
                'get_points': '获得积分',
                'confirm_recharge_question': '确认充值？',
                'confirm_recharge': '确认充值',
                'recharge_success': '充值成功',
                'payment_order_id': '支付订单号',
                'recharge_failed': '充值失败',
                'input_error': '输入错误',
                'system_error': '系统错误',
                'creating_payment_order': '正在创建支付订单...',
                'create_order_failed': '创建支付订单失败，请检查网络连接',
                'order_created_complete_payment': '支付订单创建成功，请完成支付...',
                'user_cancelled_payment': '用户取消支付',
                'waiting_payment_complete': '等待支付完成...',
                'payment_success': '支付成功',
                'payment_failed': '支付失败',
                'payment_timeout': '支付超时，请稍后查看支付结果或联系客服',
                'payment_exception': '支付处理异常',
                'scan_payment': '扫码支付',
                'scan_qr_to_pay': '请使用手机扫描下方二维码完成支付',
                'qr_generation_failed': '二维码生成失败',
                'payment_auto_detect': '支付完成后，系统将自动检测支付状态',
                'cancel_payment': '取消支付',
                'payment_completed': '已完成支付',
                'qr_dialog_exception': '显示二维码对话框异常',
                'points': '积分',
                'recharge': '充值',
                'transaction_history': '交易记录',
                'steam_account': 'Steam账户',
                'bind_steam_account': '绑定Steam账户',
                'steam_id': 'Steam ID',
                'exchange_rate': '兑换比例',
                'test_user': '测试用户',
                
                # 商城页面额外翻译
                'no_image': '暂无图片',
                'stock': '库存',
                'buy': '购买',
                'return_to_shop': '🏠 返回商城',
                'no_products': '暂无商品',
                'points_unit': '积分',
                'stock_unit': '库存',
                'unit_price': '单价',
                'subtotal': '小计',
                'remove_from_cart': '删除',
                'confirm_delete': '确认删除',
                'confirm_remove_item': '确定要从购物车中移除此商品吗？',
                'cart_empty': '购物车为空',
                'insufficient_points': '积分不足',
                'insufficient_points_msg': '您的积分不足，需要 {total_points} 积分',
                'confirm_checkout': '确认结算',
                'confirm_checkout_msg': '确定要花费 {total_points} 积分购买这些商品吗？',
                'order_success': '订单创建成功！',
                'order_failed': '创建订单失败',
                'update_quantity_failed': '更新数量失败',
                'remove_item_failed': '移除商品失败',
                'please_login_to_shop': '请先登录',
                'insufficient_stock': '商品库存不足',
                'add_to_cart_success': '商品已加入购物车',
                'add_to_cart_failed': '加入购物车失败',
                
                # 注册页面额外翻译
                'image_captcha': '图片验证码',
                'enter_captcha': '请输入图片中的4位数字',
                'refresh_captcha': '刷新验证码',
                'enter_image_captcha': '请输入图片中的验证码',
                'captcha_success': '✓ 验证成功',
                'captcha_error': '❌ 验证码错误，请重新输入',
                'enter_4_digits': '请输入4位数字',
                'bind_steam_account_checkbox': '绑定Steam账号',
                'steam_login_button': '使用Steam账号登录',
                'steam_login_browser': '请在浏览器中完成Steam登录授权',
                'steam_login_failed': 'Steam登录失败',
                'steam_bind_success_msg': 'Steam账号绑定成功',
                'email_format_error': '邮箱格式不正确',
                'email_validation_success': '邮箱验证通过',
                'fill_required_fields': '请填写所有必填字段',
                'password_min_length': '密码长度不能少于6位',
                'complete_captcha': '请完成图片验证码验证',
                'invalid_invite_code': '邀请码无效或已被使用',
                'registration_success': '注册成功！',
                'registration_failed': '注册失败',
                
                # 登录页面额外翻译
                'welcome_to': '欢迎来到',
                'your_exclusive_game_store': '您的专属游戏商城',
                'enter_username_password': '请输入用户名和密码',
                'username_password_error': '用户名或密码错误',
                'no_account_yet': '还没有账户？',
                'register_now': '立即注册',
                'prompt': '提示',
                
                # 主窗口额外翻译
                'account_banned': '账户被封禁',
                'account_banned_msg': '您的账户已被封禁，有问题请联系管理员。',
                'farewell': '离别',
                'confirm_exit': '你确定要离开我吗?宝宝',
                'confirm_button': '确定',
                'cancel_button': '取消',
                
                # 插件管理页面
                'plugin_management': '插件管理',
                'install_plugin': '安装插件',
                'plugin_name': '插件名称',
                'version': '版本',
                'select_plugin_file': '选择插件文件',
                'plugin_install_success': '插件安装成功',
                'plugin_install_failed': '插件安装失败',
                
                # 管理员页面
                'admin_title': '管理员面板',
                'product_management': '商品管理',
                'user_management': '用户管理',
                'order_management': '订单管理',
                'system_settings': '系统设置',
                'add_product': '添加商品',
                'edit_product': '编辑商品',
                'delete_product': '删除商品',
                'product_name': '商品名称',
                'product_price': '商品价格',
                'product_description': '商品描述',
                'product_stock': '商品库存',
                'add_admin': '添加管理员',
                'user_type': '用户类型',
                'status': '状态',
                'actions': '操作',
                'back_to_shop': '返回商城',
                
                # CSGO服务器页面
                'csgo_title': 'CSGO服务器查询',
                'server_name': '服务器名称',
                'server_ip': '服务器IP',
                'players': '玩家数',
                'map': '地图',
                'ping': '延迟',
                'refresh': '刷新',
                'connect': '连接',
                
                # 通用按钮和消息
                'save': '保存',
                'cancel': '取消',
                'confirm': '确认',
                'delete': '删除',
                'edit': '编辑',
                'add': '添加',
                'back': '返回',
                'next': '下一步',
                'previous': '上一步',
                'close': '关闭',
                'ok': '确定',
                'yes': '是',
                'no': '否',
                
                # 消息提示
                'success': '成功',
                'error': '错误',
                'warning': '警告',
                'info': '信息',
                'login_success': '登录成功',
                'login_failed': '登录失败',
                'register_success': '注册成功',
                'register_failed': '注册失败',
                'operation_success': '操作成功',
                'operation_failed': '操作失败',
                'please_login': '请先登录',
                'no_permission': '无权限访问',
                'invalid_input': '输入无效',
                'network_error': '网络错误',
                'server_error': '服务器错误',
            },
            'en': {
                # Main Window
                'app_title': 'Hurricane Community Store',
                'login': 'Login',
                'register': 'Register',
                'home': 'Shop',
                'cart': 'Cart',
                'unit_price': 'Unit Price',
                'subtotal': 'Subtotal',
                'quantity': 'Quantity',
                'remove': 'Remove',
                'update_quantity_failed': 'Failed to update quantity',
                'confirm_remove_item': 'Are you sure you want to remove this item from cart?',
                'remove_item_failed': 'Failed to remove item',
                'please_login_first': 'Please login first',
                'cart_empty': 'Cart is empty',
                'insufficient_points': 'Insufficient Points',
                'insufficient_points_message': 'Your points are insufficient, need',
                'confirm_checkout': 'Confirm Checkout',
                'confirm_spend': 'Are you sure you want to spend',
                'buy_items': ' to buy these items',
                'order_created_success': 'Order created successfully!',
                'create_order_failed': 'Failed to create order',
                'profile': 'Profile',
                'admin': 'Admin',
                'csgo_server': 'CSGO Server',
                'logout': 'Logout',
                'language': 'Language',
                'switch_to_english': 'Switch to English',
                'switch_to_chinese': 'Switch to Chinese',
                
                # Login Page
                'username': 'Username',
                'password': 'Password',
                'login_button': 'Login',
                'register_button': 'Register',
                'back_to_login': 'Back to Login',
                'forgot_password': 'Forgot Password',
                'remember_me': 'Remember Me',
                
                # Register Page
                'confirm_password': 'Confirm Password',
                'email': 'Email',
                'register_title': 'User Registration',
                'confirm_register': 'Confirm Registration',
                'steam_bind': 'Steam Binding',
                'bind_steam': 'Bind Steam',
                
                # Shop Page
                'shop_title': 'Shop',
                'product_name': 'Product Name',
                'price': 'Price',
                'description': 'Description',
                'add_to_cart': 'Add to Cart',
                'buy_now': 'Buy Now',
                'search': 'Search',
                'category': 'Category',
                'all_categories': 'All Categories',
                
                # Cart Page
                'cart_title': 'Shopping Cart',
                'quantity': 'Quantity',
                'total': 'Total',
                'checkout': 'Checkout',
                'remove': 'Remove',
                'clear_cart': 'Clear Cart',
                'empty_cart': 'Cart is Empty',
                
                # Profile Page
                'profile_title': 'User Profile',
                'personal_center': '👤 Personal Center',
                'user_info': '📋 User Information',
                'steam_account_binding': '🎮 Steam Account Binding',
                'enter_steam_id': 'Please enter your Steam ID',
                'bind_steam': '🔗 Bind Steam',
                'points_recharge': '💰 Points Recharge',
                'current_exchange_rate': '⭐ Current Exchange Rate: 1 Yuan = {exchange_rate} Points',
                'recharge_amount': '💳 Recharge Amount:',
                'enter_amount_yuan': 'Please enter recharge amount (Yuan)',
                'will_get_points': 'Will get points: {points}',
                'will_get_points_0': 'Will get points: 0',
                'payment_method': '💰 Payment Method:',
                'recharge_now': '🚀 Recharge Now',
                'transaction_records': '📊 Transaction Records',
                'time': 'Time',
                'type': 'Type',
                'amount': 'Amount',
                'description': 'Description',
                'username_label': 'Username',
                'account_type': 'Account Type',
                'display_name': 'Display Name',
                'email': 'Email',
                'points_balance': 'Points Balance',
                'steam_account': 'Steam Account',
                'not_bound_steam': 'Steam account not bound',
                'please_login_first': 'Please login first',
                'please_enter_steam_id': 'Please enter Steam ID',
                'steam_bind_success': 'Steam account bound successfully',
                'bind_failed': 'Binding failed',
                'amount_must_greater_zero': 'Recharge amount must be greater than 0',
                'max_recharge_limit': 'Single recharge amount cannot exceed 10000 Yuan',
                'recharge_confirmation': 'Recharge Information Confirmation',
                'payment_amount': 'Payment Amount',
                'get_points': 'Get Points',
                'confirm_recharge_question': 'Confirm recharge?',
                'confirm_recharge': 'Confirm Recharge',
                'recharge_success': 'Recharge successful',
                'back_to_shop': 'Back to Shop',
                'change_avatar': 'Change Avatar',
                'new_username': 'New Username',
                'new_email': 'New Email',
                'new_password': 'New Password',
                'save_changes': 'Save Changes',
                'points_records': 'Points Records',
                'no_avatar': 'No Avatar',
                'select_avatar': 'Select Avatar',
                'image_files': 'Image Files (*.png *.jpg *.jpeg *.bmp *.gif)',
                'cannot_load_image': 'Cannot load image',
                'avatar_update_success': 'Avatar updated successfully',
                'save_avatar_failed': 'Failed to save avatar',
                'update_avatar_failed': 'Failed to update avatar',
                'steam_account': 'Steam Account',
                'unbind_steam': 'Unbind Steam',
                'callback_server_failed': 'Failed to start callback server',
                'complete_steam_auth': 'Please complete Steam login authorization in browser',
                'steam_bind_failed': 'Failed to start Steam binding',
                'confirm_unbind': 'Confirm Unbind',
                'confirm_unbind_steam': 'Are you sure you want to unbind Steam account?',
                'steam_unbound': 'Steam account unbound',
                'unbind_failed': 'Unbind failed',
                'steam_login_verify_failed': 'Steam login verification failed',
                'steam_bind_success': 'Steam account bound successfully',
                'handle_steam_callback_failed': 'Failed to handle Steam callback',
                'user_not_exist': 'User does not exist',
                'no_changes_to_save': 'No changes to save',
                'invalid_email_format': 'Invalid email format',
                'profile_update_success': 'Profile updated successfully',
                'save_failed': 'Save failed',
                'no_image': 'No Image',
                'stock': 'Stock',
                'buy': 'Buy',
                'cart': 'Cart',
                'payment_order_id': 'Payment Order ID',
                'recharge_failed': 'Recharge failed',
                'input_error': 'Input error',
                'system_error': 'System error',
                'creating_payment_order': 'Creating payment order...',
                'create_order_failed': 'Failed to create payment order, please check network connection',
                'order_created_complete_payment': 'Payment order created successfully, please complete payment...',
                'user_cancelled_payment': 'User cancelled payment',
                'waiting_payment_complete': 'Waiting for payment completion...',
                'payment_success': 'Payment successful',
                'payment_failed': 'Payment failed',
                'payment_timeout': 'Payment timeout, please check payment result later or contact customer service',
                'payment_exception': 'Payment processing exception',
                'scan_payment': 'Scan Payment',
                'scan_qr_to_pay': 'Please use your phone to scan the QR code below to complete payment',
                'qr_generation_failed': 'QR code generation failed',
                'payment_auto_detect': 'After payment completion, the system will automatically detect payment status',
                'cancel_payment': 'Cancel Payment',
                'payment_completed': 'Payment Completed',
                'qr_dialog_exception': 'QR code dialog exception',
                'points': 'Points',
                'recharge': 'Recharge',
                'transaction_history': 'Transaction History',
                'steam_account': 'Steam Account',
                'bind_steam_account': 'Bind Steam Account',
                'steam_id': 'Steam ID',
                'exchange_rate': 'Exchange Rate',
                
                # Shop Page Additional Translations
                'no_image': 'No Image',
                'stock': 'Stock',
                'buy': 'Buy',
                'return_to_shop': '🏠 Return to Shop',
                'no_products': 'No Products',
                'points_unit': 'Points',
                'stock_unit': 'Stock',
                'unit_price': 'Unit Price',
                'subtotal': 'Subtotal',
                'remove_from_cart': 'Remove',
                'confirm_delete': 'Confirm Delete',
                'confirm_remove_item': 'Are you sure you want to remove this item from cart?',
                'cart_empty': 'Cart is Empty',
                'insufficient_points': 'Insufficient Points',
                'insufficient_points_msg': 'Your points are insufficient, need {total_points} points',
                'confirm_checkout': 'Confirm Checkout',
                'confirm_checkout_msg': 'Are you sure you want to spend {total_points} points to buy these items?',
                'order_success': 'Order created successfully!',
                'order_failed': 'Failed to create order',
                'update_quantity_failed': 'Failed to update quantity',
                'remove_item_failed': 'Failed to remove item',
                'please_login_to_shop': 'Please login first',
                'insufficient_stock': 'Insufficient stock',
                'add_to_cart_success': 'Item added to cart',
                'add_to_cart_failed': 'Failed to add to cart',
                
                # Register Page Additional Translations
                'image_captcha': 'Image Captcha',
                'enter_captcha': 'Please enter the 4 digits in the image',
                'refresh_captcha': 'Refresh Captcha',
                'enter_image_captcha': 'Please enter the captcha in the image',
                'captcha_success': '✓ Verification successful',
                'captcha_error': '❌ Captcha error, please re-enter',
                'enter_4_digits': 'Please enter 4 digits',
                'bind_steam_account_checkbox': 'Bind Steam Account',
                'steam_login_button': 'Login with Steam Account',
                'steam_login_browser': 'Please complete Steam login authorization in browser',
                'steam_login_failed': 'Steam login failed',
                'steam_bind_success_msg': 'Steam account bound successfully',
                'email_format_error': 'Email format is incorrect',
                'email_validation_success': 'Email validation passed',
                'fill_required_fields': 'Please fill in all required fields',
                'password_min_length': 'Password length cannot be less than 6 characters',
                'complete_captcha': 'Please complete image captcha verification',
                'invalid_invite_code': 'Invalid or used invite code',
                'registration_success': 'Registration successful!',
                'registration_failed': 'Registration failed',
                
                # Login Page Additional Translations
                'welcome_to': 'Welcome to',
                'your_exclusive_game_store': 'Your Exclusive Game Store',
                'enter_username_password': 'Please enter username and password',
                'username_password_error': 'Username or password error',
                'no_account_yet': 'No account yet?',
                'register_now': 'Register Now',
                'prompt': 'Prompt',
                
                # Main Window Additional Translations
                'account_banned': 'Account Banned',
                'account_banned_msg': 'Your account has been banned, please contact administrator if you have any questions.',
                'farewell': 'Farewell',
                'confirm_exit': 'Are you sure you want to leave me? Baby',
                'confirm_button': 'Confirm',
                'cancel_button': 'Cancel',
                
                # Plugin Management Page
                'plugin_management': 'Plugin Management',
                'install_plugin': 'Install Plugin',
                'plugin_name': 'Plugin Name',
                'version': 'Version',
                'select_plugin_file': 'Select Plugin File',
                'plugin_install_success': 'Plugin installed successfully',
                'plugin_install_failed': 'Plugin installation failed',
                
                # Admin Page
                'admin_title': 'Admin Panel',
                'product_management': 'Product Management',
                'user_management': 'User Management',
                'order_management': 'Order Management',
                'add_product': 'Add Product',
                'edit_product': 'Edit Product',
                'delete_product': 'Delete Product',
                'add_admin': 'Add Admin',
                'user_type': 'User Type',
                'status': 'Status',
                'actions': 'Actions',
                
                # CSGO Server Page
                'csgo_title': 'CSGO Server Query',
                'server_name': 'Server Name',
                'server_ip': 'Server IP',
                'players': 'Players',
                'map': 'Map',
                'ping': 'Ping',
                'refresh': 'Refresh',
                'connect': 'Connect',
                'csgo_server_management': 'CSGO Server Management',
                'add_new_server': 'Add New Server',
                'server_name_placeholder': 'e.g.: My CSGO Server',
                'server_ip_placeholder': 'e.g.: 192.168.1.100 or example.com',
                'port': 'Port',
                'server_type': 'Server Type',
                'competitive_mode': 'Competitive',
                'casual_mode': 'Casual',
                'deathmatch': 'Deathmatch',
                'arms_race': 'Arms Race',
                'demolition': 'Demolition',
                'custom': 'Custom',
                'description_placeholder': 'Server description...',
                'add_server': 'Add Server',
                'a2s_server_query': 'A2S Server Query',
                'a2s_query_info': 'Use A2S protocol to query real-time server status',
                'server_address': 'Server Address',
                'server_address_placeholder': 'e.g.: 192.168.1.100:27015',
                'query': 'Query',
                'clear_results': 'Clear Results',
                'server_list': 'Server List',
                'no_server_info': 'No server information\n\nAdd servers or query A2S servers to view details',
                'insufficient_permissions': 'Insufficient permissions',
                'admin_only_add': 'Only administrators can add servers',
                'add_server_success': 'Server added successfully',
                'server_name_required': 'Server name cannot be empty',
                'server_ip_required': 'Server IP cannot be empty',
                'not_queried': 'Not Queried',
                'official': 'Official',
                'type': 'Type',
                'status': 'Status',
                'online': 'Online',
                'player_count': 'Players',
                'join_server': 'Join Server',
                'address': 'Address',
                'query_time': 'Query Time',
                'invalid_server_ip': 'Invalid server IP address',
                'steam_connect_confirm': 'About to open CSGO through Steam and connect to',
                'unknown_server': 'Unknown Server',
                'confirm_continue': 'Continue?',
                'steam_connect_sent': 'Connection request sent to Steam\nPlease ensure Steam and CSGO are installed',
                'steam_connect_failed': 'Unable to open Steam connection',
                'join_server_error': 'Error occurred while joining server',
                'cannot_delete': 'Cannot Delete',
                'admin_only_delete': 'Only administrators can delete servers',
                'confirm_delete': 'Confirm Delete',
                'confirm_delete_server': 'Are you sure you want to delete server',
                'enter_server_address': 'Please enter server address',
                'invalid_address_format': 'Invalid server address format\nCorrect format: IP:Port (e.g.: 192.168.1.100:27015)',
                'query_success': 'Query Success',
                'server_query_complete': 'Server query completed',
                'max_players': 'Max Players',
                'ip_address': 'IP Address',
                'game': 'Game',
                'version': 'Version',
                'protocol': 'Protocol',
                'player_list': 'Player List',
                'query_failed': 'Query Failed',
                'server_query_failed': 'Server query failed',
                'confirm_clear': 'Confirm Clear',
                'confirm_clear_results': 'Are you sure you want to clear all query results?',
                'clear_complete': 'Clear Complete',
                'results_cleared': 'Query results cleared',
                
                # Common Buttons and Messages
                'save': 'Save',
                'cancel': 'Cancel',
                'confirm': 'Confirm',
                'delete': 'Delete',
                'edit': 'Edit',
                'add': 'Add',
                'back': 'Back',
                'next': 'Next',
                'previous': 'Previous',
                'close': 'Close',
                'ok': 'OK',
                'yes': 'Yes',
                'no': 'No',
                
                # Message Prompts
                'success': 'Success',
                'error': 'Error',
                'warning': 'Warning',
                'info': 'Information',
                'login_success': 'Login Successful',
                'login_failed': 'Login Failed',
                'register_success': 'Registration Successful',
                'register_failed': 'Registration Failed',
                'operation_success': 'Operation Successful',
                'operation_failed': 'Operation Failed',
                'please_login': 'Please Login First',
                'no_permission': 'No Permission',
                'invalid_input': 'Invalid Input',
                'network_error': 'Network Error',
                'server_error': 'Server Error',
            }
        }
    
    def get_text(self, key):
        """获取当前语言的文本"""
        return self.translations.get(self.current_language, {}).get(key, key)
    
    def set_language(self, language):
        """设置当前语言"""
        if language in self.translations:
            self.current_language = language
            return True
        return False
    
    def get_current_language(self):
        """获取当前语言"""
        return self.current_language
    
    def toggle_language(self):
        """切换语言"""
        if self.current_language == 'zh':
            self.current_language = 'en'
        else:
            self.current_language = 'zh'
        return self.current_language
    
    def get_available_languages(self):
        """获取可用语言列表"""
        return list(self.translations.keys())

# 全局语言管理器实例
language_manager = LanguageManager()